import Head from "next/head";
import styled from "styled-components";
import Card from "../ui/molecules/Card";

const Title = styled.h1`
  font-weight: 200;
  font-size: 48px;
  letter-spacing: -0.9px;
  line-height: 60px;
  color: #333333;

  margin-bottom: 30px;
`;

const TopRow = styled.div`
  margin-bottom: 30px;
`;

const BottomRow = styled.div`
  display: flex;
`;

const mainBlock = {
  tag: "International",
  image: "/london-img.jpg",
  title: "London, England",
  subtitle: "Register Now",
  description:
    "Ut placet, inquam tum dicere exorsus est laborum et via procedat oratio quaerimus igitur, quid et caritatem, quae sine causa? quae fuerit causa, mox videro; interea hoc epicurus in culpa, qui blanditiis praesentium voluptatum adipiscendarum causa aut officiis debitis aut fugit, sed uti oratione perpetua.",
  date: "April 15, 2020",
  height: 402,
  width: 1170,
  imageWidth: 570,
};

const leftBlock = {
  tag: "Domestic",
  image: "/atlanta-img.png",
  title: "Atlanta, GA",
  subtitle: "Register Now",
  description: "Torquatos nostros? quos tu paulo ante cum soluta nobis est.",
  date: "March 10, 2019",
  height: 187,
  width: 570,
  imageWidth: 270,
};

const rightBlock = {
  tag: "International",
  image: "/singapore-img.jpg",
  title: "Singapore",
  subtitle: "3 Spots Left!",
  description: "Primum igitur, inquit, sic agam, ut aliquid ex eo delectu.",
  date: "February 15, 2020",
  height: 187,
  width: 570,
  imageWidth: 270,
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Regions Dyer Test</title>
        <meta name="description" content="Generated by Mike Dyer for Regions" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div style={{ marginLeft: 135 }}>
          <Title>World Traveler</Title>
          <TopRow>
            <Card
              tag={mainBlock.tag}
              image={mainBlock.image}
              imageWidth={mainBlock.imageWidth}
              title={mainBlock.title}
              description={mainBlock.description}
              subtitle={mainBlock.subtitle}
              date={mainBlock.date}
              height={mainBlock.height}
              width={mainBlock.width}
            />
          </TopRow>
          <BottomRow>
            <div style={{ marginRight: 30 }}>
              <Card
                tag={leftBlock.tag}
                image={leftBlock.image}
                imageWidth={leftBlock.imageWidth}
                title={leftBlock.title}
                description={leftBlock.description}
                subtitle={leftBlock.subtitle}
                date={leftBlock.date}
                height={leftBlock.height}
                width={leftBlock.width}
              />
            </div>

            <Card
              tag={rightBlock.tag}
              image={rightBlock.image}
              imageWidth={rightBlock.imageWidth}
              title={rightBlock.title}
              description={rightBlock.description}
              subtitle={rightBlock.subtitle}
              date={rightBlock.date}
              height={rightBlock.height}
              width={rightBlock.width}
            />
          </BottomRow>
        </div>
      </main>
    </>
  );
}
